// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCt5WFdGbsk5QsJ5-qk2U6V62ijbDdmWpc',
    appId: '1:593892671955:web:72a8c032634f9dcbb92f26',
    messagingSenderId: '593892671955',
    projectId: 'pos-farmacia-16ed3',
    authDomain: 'pos-farmacia-16ed3.firebaseapp.com',
    storageBucket: 'pos-farmacia-16ed3.firebasestorage.app',
    measurementId: 'G-L1DL4VPZ3Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBN610L7b8Lkq9WzHhl52JNy3qomJ9kSZM',
    appId: '1:593892671955:android:dc76d56917a22df8b92f26',
    messagingSenderId: '593892671955',
    projectId: 'pos-farmacia-16ed3',
    storageBucket: 'pos-farmacia-16ed3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmHd6vSSNosnyFVF-nEaJ1ODxseSmIUyo',
    appId: '1:593892671955:ios:015558439c960f72b92f26',
    messagingSenderId: '593892671955',
    projectId: 'pos-farmacia-16ed3',
    storageBucket: 'pos-farmacia-16ed3.firebasestorage.app',
    iosBundleId: 'com.example.posFarmaciaV2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmHd6vSSNosnyFVF-nEaJ1ODxseSmIUyo',
    appId: '1:593892671955:ios:015558439c960f72b92f26',
    messagingSenderId: '593892671955',
    projectId: 'pos-farmacia-16ed3',
    storageBucket: 'pos-farmacia-16ed3.firebasestorage.app',
    iosBundleId: 'com.example.posFarmaciaV2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCt5WFdGbsk5QsJ5-qk2U6V62ijbDdmWpc',
    appId: '1:593892671955:web:09cede4fb936f93cb92f26',
    messagingSenderId: '593892671955',
    projectId: 'pos-farmacia-16ed3',
    authDomain: 'pos-farmacia-16ed3.firebaseapp.com',
    storageBucket: 'pos-farmacia-16ed3.firebasestorage.app',
    measurementId: 'G-16PR3H6JX4',
  );
}
